### PR TITLE
exoscale: rename exo into exoscale

### PR DESCRIPTION
**Pull request by greut**
A minor nitpick with the _exo_ name and a little addition for the AAAA record (to be future proof).

Thanks for the great work. I'll see if I can get it to work on a minikube.

### CODE REVIEW

**Comment by greut** [comment]
it works!! brilliant

screenshot from 2018-07-04 08-26-16

**Comment by FaKod** [comment]
@greut I think you'll have to do this now :-) https://github.com/kubernetes-incubator/external-dns/blob/master/CONTRIBUTING.md

**Comment by greut** [comment]
@FaKod great! time to CLA.

**Comment by FaKod** [comment]
@greut What happened here is, that I rebased my changes to one commit this morning. But you didn't pull them and I merged your branch in mine. So I think we should do that again, to get a clean pull request, ok?

**Comment by FaKod** [comment]
@greut I've made a new branch external-dns-exoscale. Can you reissue your changes there please? (sorry for the noise)

**Pull request merged**
